#!/usr/bin/ksh
rman target=/ << EOF
run {
CONFIGURE BACKUP OPTIMIZATION OFF;
CONFIGURE CONTROLFILE AUTOBACKUP OFF;
CONFIGURE ENCRYPTION FOR DATABASE OFF;
CONFIGURE MAXSETSIZE TO UNLIMITED;
CONFIGURE DEVICE TYPE 'SBT_TAPE' CLEAR;
}
exit;
EOF
